import Foundation
import SwiftUI

struct DMCThread {
    let number: String
    let name: String
    let color: String
}

func getColorForDMCThread(_ color: String) -> Color {
    switch color.lowercased() {
    case "white": return .white
    case "ecru": return Color(red: 0.95, green: 0.91, blue: 0.84)
    case "b5200": return .white
    case "blanc": return .white
    case "black": return .black
    case "310": return .black
    case "white tin": return Color(red: 0.95, green: 0.95, blue: 0.95)
    case "tin": return Color(red: 0.75, green: 0.75, blue: 0.75)
    case "pink": return .pink
    case "coral": return Color(red: 1.0, green: 0.5, blue: 0.31)
    case "rose": return Color(red: 1.0, green: 0.41, blue: 0.7)
    case "red": return .red
    case "burgundy": return Color(red: 0.5, green: 0.0, blue: 0.13)
    case "orange": return .orange
    case "yellow": return .yellow
    case "green": return .green
    case "blue": return .blue
    case "purple": return .purple
    case "brown": return .brown
    case "cream": return Color(red: 1.0, green: 0.99, blue: 0.82)
    case "beige": return Color(red: 0.96, green: 0.96, blue: 0.86)
    case "ivory": return Color(red: 1.0, green: 1.0, blue: 0.94)
    case "peach": return Color(red: 1.0, green: 0.85, blue: 0.73)
    case "salmon": return Color(red: 0.98, green: 0.5, blue: 0.45)
    case "rust": return Color(red: 0.72, green: 0.25, blue: 0.05)
    case "gold": return Color(red: 1.0, green: 0.84, blue: 0.0)
    case "olive": return Color(red: 0.5, green: 0.5, blue: 0.0)
    case "teal": return Color(red: 0.0, green: 0.5, blue: 0.5)
    case "navy": return Color(red: 0.0, green: 0.0, blue: 0.5)
    case "lavender": return Color(red: 0.9, green: 0.9, blue: 0.98)
    case "lilac": return Color(red: 0.78, green: 0.64, blue: 0.78)
    case "wine": return Color(red: 0.45, green: 0.0, blue: 0.09)
    case "copper": return Color(red: 0.72, green: 0.45, blue: 0.2)
    case "silver": return Color(red: 0.75, green: 0.75, blue: 0.75)
    case "bronze": return Color(red: 0.8, green: 0.5, blue: 0.2)
    default: return .primary
    }
}

func getAllDMCThreads() -> [DMCThread] {
    return [
        DMCThread(number: "B5200", name: "Snow White", color: "White"),
        DMCThread(number: "Blanc", name: "White", color: "White"),
        DMCThread(number: "Ecru", name: "Ecru", color: "Ecru"),
        DMCThread(number: "150", name: "Dusty Rose - Ultra Very Dark", color: "Red"),
        DMCThread(number: "151", name: "Dusty Rose - Very Light", color: "Pink"),
        DMCThread(number: "152", name: "Shell Pink - Medium Light", color: "Pink"),
        DMCThread(number: "153", name: "Violet - Very Light", color: "Purple"),
        DMCThread(number: "154", name: "Grape - Very Dark", color: "Purple"),
        DMCThread(number: "155", name: "Blue Violet - Medium Dark", color: "Purple"),
        DMCThread(number: "156", name: "Blue Violet - Medium Light", color: "Purple"),
        DMCThread(number: "157", name: "Cornflower Blue - Very Light", color: "Blue"),
        DMCThread(number: "158", name: "Cornflower Blue - Medium Very Dark", color: "Blue"),
        DMCThread(number: "159", name: "Gray Blue - Light", color: "Blue"),
        DMCThread(number: "160", name: "Gray Blue - Medium", color: "Blue"),
        DMCThread(number: "161", name: "Gray Blue - Medium Dark", color: "Blue"),
        DMCThread(number: "162", name: "Blue - Ultra Very Light", color: "Blue"),
        DMCThread(number: "163", name: "Celadon Green - Medium", color: "Green"),
        DMCThread(number: "164", name: "Forest Green - Light", color: "Green"),
        DMCThread(number: "165", name: "Moss Green - Very Light", color: "Green"),
        DMCThread(number: "166", name: "Moss Green - Medium Light", color: "Green"),
        DMCThread(number: "167", name: "Yellow Beige - Very Dark", color: "Brown"),
        DMCThread(number: "168", name: "Pewter - Very Light", color: "Gray"),
        DMCThread(number: "169", name: "Pewter - Light", color: "Gray"),
        DMCThread(number: "208", name: "Lavender - Very Dark", color: "Purple"),
        DMCThread(number: "209", name: "Lavender - Dark", color: "Purple"),
        DMCThread(number: "210", name: "Lavender - Medium", color: "Purple"),
        DMCThread(number: "211", name: "Lavender - Light", color: "Purple"),
        DMCThread(number: "221", name: "Shell Pink - Very Dark", color: "Red"),
        DMCThread(number: "223", name: "Shell Pink - Light", color: "Pink"),
        DMCThread(number: "224", name: "Shell Pink - Very Light", color: "Pink"),
        DMCThread(number: "225", name: "Shell Pink - Ultra Very Light", color: "Pink"),
        DMCThread(number: "300", name: "Mahogany - Very Dark", color: "Brown"),
        DMCThread(number: "301", name: "Mahogany - Medium", color: "Brown"),
        DMCThread(number: "302", name: "Brown - Medium", color: "Brown"),
        DMCThread(number: "303", name: "Desert Sand - Light", color: "Brown"),
        DMCThread(number: "304", name: "Red - Medium", color: "Red"),
        DMCThread(number: "307", name: "Lemon - Very Bright", color: "Yellow"),
        DMCThread(number: "309", name: "Rose - Dark", color: "Red"),
        DMCThread(number: "310", name: "Black", color: "Black"),
        DMCThread(number: "311", name: "Wedgewood - Medium", color: "Blue"),
        DMCThread(number: "312", name: "Baby Blue - Very Dark", color: "Blue"),
        DMCThread(number: "315", name: "Antique Mauve - Medium Dark", color: "Purple"),
        DMCThread(number: "316", name: "Antique Mauve - Medium", color: "Purple"),
        DMCThread(number: "317", name: "Pewter Gray", color: "Gray"),
        DMCThread(number: "318", name: "Steel Gray - Light", color: "Gray"),
        DMCThread(number: "319", name: "Pistachio Green - Very Dark", color: "Green"),
        DMCThread(number: "320", name: "Pistachio Green - Medium", color: "Green"),
        DMCThread(number: "321", name: "Red", color: "Red"),
        DMCThread(number: "322", name: "Baby Blue - Dark", color: "Blue"),
        DMCThread(number: "326", name: "Rose - Very Dark", color: "Red"),
        DMCThread(number: "327", name: "Violet - Very Dark", color: "Purple"),
        DMCThread(number: "333", name: "Blue Violet - Very Dark", color: "Purple"),
        DMCThread(number: "334", name: "Baby Blue - Medium", color: "Blue"),
        DMCThread(number: "335", name: "Rose", color: "Red"),
        DMCThread(number: "336", name: "Navy Blue", color: "Blue"),
        DMCThread(number: "340", name: "Blue Violet - Medium", color: "Purple"),
        DMCThread(number: "341", name: "Blue Violet - Light", color: "Purple"),
        DMCThread(number: "347", name: "Salmon - Very Dark", color: "Red"),
        DMCThread(number: "349", name: "Coral - Dark", color: "Red"),
        DMCThread(number: "350", name: "Coral - Medium", color: "Red"),
        DMCThread(number: "351", name: "Coral", color: "Red"),
        DMCThread(number: "352", name: "Coral - Light", color: "Red"),
        DMCThread(number: "353", name: "Peach", color: "Orange"),
        DMCThread(number: "355", name: "Terra Cotta - Dark", color: "Brown"),
        DMCThread(number: "356", name: "Terra Cotta - Medium", color: "Brown"),
        DMCThread(number: "367", name: "Pistachio Green - Dark", color: "Green"),
        DMCThread(number: "368", name: "Pistachio Green - Light", color: "Green"),
        DMCThread(number: "369", name: "Pistachio Green - Very Light", color: "Green"),
        DMCThread(number: "370", name: "Mustard - Medium", color: "Yellow"),
        DMCThread(number: "371", name: "Mustard", color: "Yellow"),
        DMCThread(number: "372", name: "Mustard - Light", color: "Yellow"),
        DMCThread(number: "400", name: "Mahogany - Dark", color: "Brown"),
        DMCThread(number: "402", name: "Mahogany - Very Light", color: "Brown"),
        DMCThread(number: "407", name: "Desert Sand - Medium", color: "Brown"),
        DMCThread(number: "413", name: "Pewter Gray - Dark", color: "Gray"),
        DMCThread(number: "414", name: "Steel Gray - Dark", color: "Gray"),
        DMCThread(number: "415", name: "Pearl Gray", color: "Gray"),
        DMCThread(number: "420", name: "Hazel Nut Brown - Dark", color: "Brown"),
        DMCThread(number: "422", name: "Hazel Nut Brown - Light", color: "Brown"),
        DMCThread(number: "433", name: "Brown - Medium", color: "Brown"),
        DMCThread(number: "434", name: "Brown - Light", color: "Brown"),
        DMCThread(number: "435", name: "Brown - Very Light", color: "Brown"),
        DMCThread(number: "436", name: "Tan", color: "Brown"),
        DMCThread(number: "437", name: "Tan - Light", color: "Brown"),
        DMCThread(number: "444", name: "Lemon - Dark", color: "Yellow"),
        DMCThread(number: "445", name: "Lemon - Light", color: "Yellow"),
        DMCThread(number: "451", name: "Shell Gray - Dark", color: "Gray"),
        DMCThread(number: "452", name: "Shell Gray - Medium", color: "Gray"),
        DMCThread(number: "453", name: "Shell Gray - Light", color: "Gray"),
        DMCThread(number: "469", name: "Avocado Green", color: "Green"),
        DMCThread(number: "470", name: "Avocado Green - Light", color: "Green"),
        DMCThread(number: "471", name: "Avocado Green - Very Light", color: "Green"),
        DMCThread(number: "472", name: "Avocado Green - Ultra Very Light", color: "Green"),
        DMCThread(number: "498", name: "Red - Dark", color: "Red"),
        DMCThread(number: "500", name: "Blue Green - Very Dark", color: "Green"),
        DMCThread(number: "501", name: "Blue Green - Dark", color: "Green"),
        DMCThread(number: "502", name: "Blue Green", color: "Green"),
        DMCThread(number: "503", name: "Blue Green - Medium", color: "Green"),
        DMCThread(number: "504", name: "Blue Green - Light", color: "Green"),
        DMCThread(number: "505", name: "Jade Green", color: "Green"),
        DMCThread(number: "517", name: "Wedgewood - Dark", color: "Blue"),
        DMCThread(number: "518", name: "Wedgewood - Light", color: "Blue"),
        DMCThread(number: "519", name: "Sky Blue", color: "Blue"),
        DMCThread(number: "520", name: "Fern Green - Dark", color: "Green"),
        DMCThread(number: "522", name: "Fern Green", color: "Green"),
        DMCThread(number: "523", name: "Fern Green - Light", color: "Green"),
        DMCThread(number: "524", name: "Fern Green - Very Light", color: "Green"),
        DMCThread(number: "535", name: "Ash Gray - Very Light", color: "Gray"),
        DMCThread(number: "543", name: "Beige Brown - Ultra Very Light", color: "Brown"),
        DMCThread(number: "550", name: "Violet - Very Dark", color: "Purple"),
        DMCThread(number: "552", name: "Violet - Medium", color: "Purple"),
        DMCThread(number: "553", name: "Violet", color: "Purple"),
        DMCThread(number: "554", name: "Violet - Light", color: "Purple"),
        DMCThread(number: "561", name: "Celadon Green - Very Dark", color: "Green"),
        DMCThread(number: "562", name: "Jade - Medium", color: "Green"),
        DMCThread(number: "563", name: "Jade - Light", color: "Green"),
        DMCThread(number: "564", name: "Jade - Very Light", color: "Green"),
        DMCThread(number: "580", name: "Moss Green - Dark", color: "Green"),
        DMCThread(number: "581", name: "Moss Green", color: "Green"),
        DMCThread(number: "597", name: "Turquoise", color: "Blue"),
        DMCThread(number: "598", name: "Turquoise - Light", color: "Blue"),
        DMCThread(number: "600", name: "Cranberry - Very Dark", color: "Red"),
        DMCThread(number: "601", name: "Cranberry - Dark", color: "Red"),
        DMCThread(number: "602", name: "Cranberry - Medium", color: "Red"),
        DMCThread(number: "603", name: "Cranberry", color: "Red"),
        DMCThread(number: "604", name: "Cranberry - Light", color: "Red"),
        DMCThread(number: "605", name: "Cranberry - Very Light", color: "Red"),
        DMCThread(number: "606", name: "Orange-Red - Bright", color: "Orange"),
        DMCThread(number: "608", name: "Orange-Red - Bright", color: "Orange"),
        DMCThread(number: "610", name: "Drab Brown - Very Dark", color: "Brown"),
        DMCThread(number: "611", name: "Drab Brown", color: "Brown"),
        DMCThread(number: "612", name: "Drab Brown - Light", color: "Brown"),
        DMCThread(number: "613", name: "Drab Brown - Very Light", color: "Brown"),
        DMCThread(number: "632", name: "Desert Sand - Ultra Very Dark", color: "Brown"),
        DMCThread(number: "640", name: "Beige Gray - Very Dark", color: "Gray"),
        DMCThread(number: "642", name: "Beige Gray - Dark", color: "Gray"),
        DMCThread(number: "644", name: "Beige Gray - Medium", color: "Gray"),
        DMCThread(number: "645", name: "Beige Gray - Light", color: "Gray"),
        DMCThread(number: "646", name: "Beaver Gray - Medium", color: "Gray"),
        DMCThread(number: "647", name: "Beaver Gray - Light", color: "Gray"),
        DMCThread(number: "648", name: "Beaver Gray - Very Light", color: "Gray"),
        DMCThread(number: "666", name: "Bright Red", color: "Red"),
        DMCThread(number: "676", name: "Old Gold - Light", color: "Yellow"),
        DMCThread(number: "677", name: "Old Gold - Very Light", color: "Yellow"),
        DMCThread(number: "680", name: "Old Gold - Dark", color: "Yellow"),
        DMCThread(number: "699", name: "Green", color: "Green"),
        DMCThread(number: "700", name: "Green - Bright", color: "Green"),
        DMCThread(number: "701", name: "Green - Light", color: "Green"),
        DMCThread(number: "702", name: "Kelly Green", color: "Green"),
        DMCThread(number: "703", name: "Chartreuse", color: "Green"),
        DMCThread(number: "704", name: "Chartreuse - Bright", color: "Green"),
        DMCThread(number: "712", name: "Cream", color: "White"),
        DMCThread(number: "718", name: "Plum", color: "Purple"),
        DMCThread(number: "720", name: "Orange Spice - Dark", color: "Orange"),
        DMCThread(number: "721", name: "Orange Spice - Medium", color: "Orange"),
        DMCThread(number: "722", name: "Orange Spice - Light", color: "Orange"),
        DMCThread(number: "725", name: "Topaz - Medium Light", color: "Yellow"),
        DMCThread(number: "726", name: "Topaz - Light", color: "Yellow"),
        DMCThread(number: "727", name: "Topaz - Very Light", color: "Yellow"),
        DMCThread(number: "729", name: "Old Gold - Medium", color: "Yellow"),
        DMCThread(number: "730", name: "Olive Green - Very Dark", color: "Green"),
        DMCThread(number: "731", name: "Olive Green - Dark", color: "Green"),
        DMCThread(number: "732", name: "Olive Green", color: "Green"),
        DMCThread(number: "733", name: "Olive Green - Medium", color: "Green"),
        DMCThread(number: "734", name: "Olive Green - Light", color: "Green"),
        DMCThread(number: "738", name: "Tan - Very Light", color: "Brown"),
        DMCThread(number: "739", name: "Tan - Ultra Very Light", color: "Brown"),
        DMCThread(number: "740", name: "Tangerine", color: "Orange"),
        DMCThread(number: "741", name: "Tangerine - Medium", color: "Orange"),
        DMCThread(number: "742", name: "Tangerine - Light", color: "Orange"),
        DMCThread(number: "743", name: "Yellow - Medium", color: "Yellow"),
        DMCThread(number: "744", name: "Yellow - Pale", color: "Yellow"),
        DMCThread(number: "745", name: "Yellow - Light Pale", color: "Yellow"),
        DMCThread(number: "746", name: "Off White", color: "White"),
        DMCThread(number: "747", name: "Peacock Blue - Very Light", color: "Blue"),
        DMCThread(number: "754", name: "Peach - Light", color: "Orange"),
        DMCThread(number: "758", name: "Terra Cotta - Very Light", color: "Brown"),
        DMCThread(number: "760", name: "Salmon", color: "Red"),
        DMCThread(number: "761", name: "Salmon - Light", color: "Red"),
        DMCThread(number: "762", name: "Pearl Gray - Very Light", color: "Gray"),
        DMCThread(number: "772", name: "Yellow Green - Very Light", color: "Green"),
        DMCThread(number: "775", name: "Baby Blue - Very Light", color: "Blue"),
        DMCThread(number: "776", name: "Pink - Medium", color: "Pink"),
        DMCThread(number: "777", name: "Raspberry - Very Dark", color: "Red"),
        DMCThread(number: "778", name: "Antique Mauve - Very Light", color: "Purple"),
        DMCThread(number: "779", name: "Cocoa - Dark", color: "Brown"),
        DMCThread(number: "780", name: "Topaz - Ultra Very Dark", color: "Yellow"),
        DMCThread(number: "781", name: "Topaz - Very Dark", color: "Yellow"),
        DMCThread(number: "782", name: "Topaz - Dark", color: "Yellow"),
        DMCThread(number: "783", name: "Topaz - Medium", color: "Yellow"),
        DMCThread(number: "791", name: "Cornflower Blue - Very Dark", color: "Blue"),
        DMCThread(number: "792", name: "Cornflower Blue - Dark", color: "Blue"),
        DMCThread(number: "793", name: "Cornflower Blue - Medium", color: "Blue"),
        DMCThread(number: "794", name: "Cornflower Blue - Light", color: "Blue"),
        DMCThread(number: "796", name: "Royal Blue - Dark", color: "Blue"),
        DMCThread(number: "797", name: "Royal Blue", color: "Blue"),
        DMCThread(number: "798", name: "Delft Blue - Dark", color: "Blue"),
        DMCThread(number: "799", name: "Delft Blue - Medium", color: "Blue"),
        DMCThread(number: "800", name: "Delft Blue - Pale", color: "Blue"),
        DMCThread(number: "801", name: "Coffee Brown - Dark", color: "Brown"),
        DMCThread(number: "803", name: "Baby Blue - Ultra Very Dark", color: "Blue"),
        DMCThread(number: "806", name: "Peacock Blue - Dark", color: "Blue"),
        DMCThread(number: "807", name: "Peacock Blue", color: "Blue"),
        DMCThread(number: "809", name: "Delft Blue", color: "Blue"),
        DMCThread(number: "813", name: "Blue - Light", color: "Blue"),
        DMCThread(number: "814", name: "Garnet - Dark", color: "Red"),
        DMCThread(number: "815", name: "Garnet - Medium", color: "Red"),
        DMCThread(number: "816", name: "Garnet", color: "Red"),
        DMCThread(number: "817", name: "Coral Red - Very Dark", color: "Red"),
        DMCThread(number: "818", name: "Baby Pink", color: "Pink"),
        DMCThread(number: "819", name: "Baby Pink - Light", color: "Pink"),
        DMCThread(number: "820", name: "Royal Blue - Very Dark", color: "Blue"),
        DMCThread(number: "822", name: "Beige Gray - Light", color: "Gray"),
        DMCThread(number: "823", name: "Navy Blue - Dark", color: "Blue"),
        DMCThread(number: "824", name: "Blue - Very Dark", color: "Blue"),
        DMCThread(number: "825", name: "Blue - Dark", color: "Blue"),
        DMCThread(number: "826", name: "Blue - Medium", color: "Blue"),
        DMCThread(number: "827", name: "Blue - Very Light", color: "Blue"),
        DMCThread(number: "828", name: "Blue - Ultra Very Light", color: "Blue"),
        DMCThread(number: "829", name: "Golden Olive - Very Dark", color: "Green"),
        DMCThread(number: "830", name: "Golden Olive - Dark", color: "Green"),
        DMCThread(number: "831", name: "Golden Olive - Medium", color: "Green"),
        DMCThread(number: "832", name: "Golden Olive", color: "Green"),
        DMCThread(number: "833", name: "Golden Olive - Light", color: "Green"),
        DMCThread(number: "834", name: "Golden Olive - Very Light", color: "Green"),
        DMCThread(number: "838", name: "Beige Brown - Very Dark", color: "Brown"),
        DMCThread(number: "839", name: "Beige Brown - Dark", color: "Brown"),
        DMCThread(number: "840", name: "Beige Brown - Medium", color: "Brown"),
        DMCThread(number: "841", name: "Beige Brown - Light", color: "Brown"),
        DMCThread(number: "842", name: "Beige Brown - Very Light", color: "Brown"),
        DMCThread(number: "844", name: "Beaver Gray - Ultra Dark", color: "Gray"),
        DMCThread(number: "869", name: "Hazel Nut Brown - Very Dark", color: "Brown"),
        DMCThread(number: "890", name: "Pistachio Green - Ultra Very Dark", color: "Green"),
        DMCThread(number: "891", name: "Carnation - Dark", color: "Red"),
        DMCThread(number: "892", name: "Carnation - Medium", color: "Red"),
        DMCThread(number: "893", name: "Carnation - Light", color: "Red"),
        DMCThread(number: "894", name: "Carnation - Very Light", color: "Red"),
        DMCThread(number: "895", name: "Hunter Green - Very Dark", color: "Green"),
        DMCThread(number: "898", name: "Coffee Brown - Very Dark", color: "Brown"),
        DMCThread(number: "899", name: "Rose - Medium", color: "Red"),
        DMCThread(number: "900", name: "Burnt Orange - Dark", color: "Orange"),
        DMCThread(number: "902", name: "Garnet - Very Dark", color: "Red"),
        DMCThread(number: "904", name: "Parrot Green - Very Dark", color: "Green"),
        DMCThread(number: "905", name: "Parrot Green - Dark", color: "Green"),
        DMCThread(number: "906", name: "Parrot Green - Medium", color: "Green"),
        DMCThread(number: "907", name: "Parrot Green - Light", color: "Green"),
        DMCThread(number: "909", name: "Emerald Green - Very Dark", color: "Green"),
        DMCThread(number: "910", name: "Emerald Green - Dark", color: "Green"),
        DMCThread(number: "911", name: "Emerald Green - Medium", color: "Green"),
        DMCThread(number: "912", name: "Emerald Green - Light", color: "Green"),
        DMCThread(number: "913", name: "Nile Green - Medium", color: "Green"),
        DMCThread(number: "915", name: "Plum - Dark", color: "Purple"),
        DMCThread(number: "917", name: "Plum - Medium", color: "Purple"),
        DMCThread(number: "918", name: "Red Copper - Dark", color: "Brown"),
        DMCThread(number: "919", name: "Red Copper", color: "Brown"),
        DMCThread(number: "920", name: "Copper - Medium", color: "Brown"),
        DMCThread(number: "921", name: "Copper", color: "Brown"),
        DMCThread(number: "922", name: "Copper - Light", color: "Brown"),
        DMCThread(number: "924", name: "Gray Green - Very Dark", color: "Green"),
        DMCThread(number: "926", name: "Gray Green - Medium", color: "Green"),
        DMCThread(number: "927", name: "Gray Green - Light", color: "Green"),
        DMCThread(number: "928", name: "Gray Green - Very Light", color: "Green"),
        DMCThread(number: "930", name: "Antique Blue - Dark", color: "Blue"),
        DMCThread(number: "931", name: "Antique Blue - Medium", color: "Blue"),
        DMCThread(number: "932", name: "Antique Blue - Light", color: "Blue"),
        DMCThread(number: "934", name: "Avocado Green - Black", color: "Green"),
        DMCThread(number: "935", name: "Avocado Green - Dark", color: "Green"),
        DMCThread(number: "936", name: "Avocado Green - Very Dark", color: "Green"),
        DMCThread(number: "937", name: "Avocado Green - Medium", color: "Green"),
        DMCThread(number: "938", name: "Coffee Brown - Ultra Dark", color: "Brown"),
        DMCThread(number: "939", name: "Navy Blue - Very Dark", color: "Blue"),
        DMCThread(number: "943", name: "Green Bright - Medium", color: "Green"),
        DMCThread(number: "945", name: "Tawny", color: "Brown"),
        DMCThread(number: "946", name: "Burnt Orange - Medium", color: "Orange"),
        DMCThread(number: "947", name: "Burnt Orange", color: "Orange"),
        DMCThread(number: "948", name: "Peach - Very Light", color: "Orange"),
        DMCThread(number: "950", name: "Desert Sand - Light", color: "Brown"),
        DMCThread(number: "951", name: "Tawny - Light", color: "Brown"),
        DMCThread(number: "954", name: "Nile Green", color: "Green"),
        DMCThread(number: "955", name: "Nile Green - Light", color: "Green"),
        DMCThread(number: "956", name: "Geranium", color: "Red"),
        DMCThread(number: "957", name: "Geranium - Pale", color: "Red"),
        DMCThread(number: "958", name: "Sea Green - Dark", color: "Green"),
        DMCThread(number: "959", name: "Sea Green - Medium", color: "Green"),
        DMCThread(number: "961", name: "Dusty Rose - Dark", color: "Red"),
        DMCThread(number: "962", name: "Dusty Rose - Medium", color: "Red"),
        DMCThread(number: "963", name: "Dusty Rose - Ultra Very Light", color: "Red"),
        DMCThread(number: "964", name: "Sea Green - Light", color: "Green"),
        DMCThread(number: "966", name: "Jade - Ultra Very Light", color: "Green"),
        DMCThread(number: "970", name: "Pumpkin - Light", color: "Orange"),
        DMCThread(number: "971", name: "Pumpkin", color: "Orange"),
        DMCThread(number: "972", name: "Canary - Deep", color: "Yellow"),
        DMCThread(number: "973", name: "Canary - Bright", color: "Yellow"),
        DMCThread(number: "975", name: "Golden Brown - Dark", color: "Brown"),
        DMCThread(number: "976", name: "Golden Brown - Medium", color: "Brown"),
        DMCThread(number: "977", name: "Golden Brown - Light", color: "Brown"),
        DMCThread(number: "986", name: "Forest Green - Very Dark", color: "Green"),
        DMCThread(number: "987", name: "Forest Green - Dark", color: "Green"),
        DMCThread(number: "988", name: "Forest Green - Medium", color: "Green"),
        DMCThread(number: "989", name: "Forest Green", color: "Green"),
        DMCThread(number: "991", name: "Aquamarine - Dark", color: "Blue"),
        DMCThread(number: "992", name: "Aquamarine - Light", color: "Blue"),
        DMCThread(number: "993", name: "Aquamarine - Very Light", color: "Blue"),
        DMCThread(number: "995", name: "Electric Blue - Dark", color: "Blue"),
        DMCThread(number: "996", name: "Electric Blue - Medium", color: "Blue"),
        DMCThread(number: "3011", name: "Khaki Green - Dark", color: "Green"),
        DMCThread(number: "3012", name: "Khaki Green - Medium", color: "Green"),
        DMCThread(number: "3013", name: "Khaki Green - Light", color: "Green"),
        DMCThread(number: "3021", name: "Brown Gray - Very Dark", color: "Gray"),
        DMCThread(number: "3022", name: "Brown Gray - Medium", color: "Gray"),
        DMCThread(number: "3023", name: "Brown Gray - Light", color: "Gray"),
        DMCThread(number: "3024", name: "Brown Gray - Very Light", color: "Gray"),
        DMCThread(number: "3031", name: "Mocha Brown - Very Dark", color: "Brown"),
        DMCThread(number: "3032", name: "Mocha Brown - Medium", color: "Brown"),
        DMCThread(number: "3033", name: "Mocha Brown - Very Light", color: "Brown"),
        DMCThread(number: "3041", name: "Antique Violet - Very Dark", color: "Purple"),
        DMCThread(number: "3042", name: "Antique Violet - Medium", color: "Purple"),
        DMCThread(number: "3045", name: "Yellow Beige - Dark", color: "Brown"),
        DMCThread(number: "3046", name: "Yellow Beige - Medium", color: "Brown"),
        DMCThread(number: "3047", name: "Yellow Beige - Light", color: "Brown"),
        DMCThread(number: "3051", name: "Green Gray - Dark", color: "Green"),
        DMCThread(number: "3052", name: "Green Gray - Medium", color: "Green"),
        DMCThread(number: "3053", name: "Green Gray - Light", color: "Green"),
        DMCThread(number: "3064", name: "Desert Sand", color: "Brown"),
        DMCThread(number: "3072", name: "Beaver Gray - Very Light", color: "Gray"),
        DMCThread(number: "3078", name: "Golden Yellow - Very Light", color: "Yellow"),
        DMCThread(number: "3325", name: "Baby Blue - Light", color: "Blue"),
        DMCThread(number: "3326", name: "Rose - Light", color: "Red"),
        DMCThread(number: "3328", name: "Salmon - Dark", color: "Red"),
        DMCThread(number: "3340", name: "Apricot - Medium", color: "Orange"),
        DMCThread(number: "3341", name: "Apricot", color: "Orange"),
        DMCThread(number: "3345", name: "Hunter Green - Dark", color: "Green"),
        DMCThread(number: "3346", name: "Hunter Green", color: "Green"),
        DMCThread(number: "3347", name: "Yellow Green - Medium", color: "Green"),
        DMCThread(number: "3348", name: "Yellow Green - Light", color: "Green"),
        DMCThread(number: "3350", name: "Dusty Rose - Ultra Dark", color: "Red"),
        DMCThread(number: "3354", name: "Dusty Rose - Light", color: "Red"),
        DMCThread(number: "3362", name: "Pine Green - Dark", color: "Green"),
        DMCThread(number: "3363", name: "Pine Green - Medium", color: "Green"),
        DMCThread(number: "3364", name: "Pine Green", color: "Green"),
        DMCThread(number: "3371", name: "Black Brown", color: "Brown"),
        DMCThread(number: "3607", name: "Plum - Light", color: "Purple"),
        DMCThread(number: "3608", name: "Plum - Very Light", color: "Purple"),
        DMCThread(number: "3609", name: "Plum - Ultra Very Light", color: "Purple"),
        DMCThread(number: "3685", name: "Mauve - Very Dark", color: "Purple"),
        DMCThread(number: "3687", name: "Mauve", color: "Purple"),
        DMCThread(number: "3688", name: "Mauve - Medium", color: "Purple"),
        DMCThread(number: "3689", name: "Mauve - Light", color: "Purple"),
        DMCThread(number: "369", name: "Pistachio Green - Very Light", color: "Green"),
        DMCThread(number: "370", name: "Mustard - Medium", color: "Yellow"),
        DMCThread(number: "371", name: "Mustard", color: "Yellow"),
        DMCThread(number: "372", name: "Mustard - Light", color: "Yellow"),
        DMCThread(number: "4000", name: "Mahogany - Dark", color: "Brown"),
        DMCThread(number: "4001", name: "Mahogany - Medium", color: "Brown"),
        DMCThread(number: "4002", name: "Mahogany - Light", color: "Brown"),
        DMCThread(number: "4003", name: "Mahogany - Very Light", color: "Brown"),
        DMCThread(number: "4004", name: "Mahogany - Ultra Very Light", color: "Brown"),
        DMCThread(number: "407", name: "Desert Sand - Medium", color: "Brown"),
        DMCThread(number: "413", name: "Pewter Gray - Dark", color: "Gray"),
        DMCThread(number: "414", name: "Steel Gray - Dark", color: "Gray"),
        DMCThread(number: "415", name: "Pearl Gray", color: "Gray"),
        DMCThread(number: "420", name: "Hazel Nut Brown - Dark", color: "Brown"),
        DMCThread(number: "422", name: "Hazel Nut Brown - Light", color: "Brown"),
        DMCThread(number: "433", name: "Brown - Medium", color: "Brown"),
        DMCThread(number: "434", name: "Brown - Light", color: "Brown"),
        DMCThread(number: "435", name: "Brown - Very Light", color: "Brown"),
        DMCThread(number: "436", name: "Tan", color: "Brown"),
        DMCThread(number: "437", name: "Tan - Light", color: "Brown"),
        DMCThread(number: "444", name: "Lemon - Dark", color: "Yellow"),
        DMCThread(number: "445", name: "Lemon - Light", color: "Yellow"),
        DMCThread(number: "451", name: "Shell Gray - Dark", color: "Gray"),
        DMCThread(number: "452", name: "Shell Gray - Medium", color: "Gray"),
        DMCThread(number: "453", name: "Shell Gray - Light", color: "Gray"),
        DMCThread(number: "469", name: "Avocado Green", color: "Green"),
        DMCThread(number: "470", name: "Avocado Green - Light", color: "Green"),
        DMCThread(number: "471", name: "Avocado Green - Very Light", color: "Green"),
        DMCThread(number: "472", name: "Avocado Green - Ultra Very Light", color: "Green"),
        DMCThread(number: "498", name: "Red - Dark", color: "Red"),
        DMCThread(number: "500", name: "Blue Green - Very Dark", color: "Green"),
        DMCThread(number: "501", name: "Blue Green - Dark", color: "Green"),
        DMCThread(number: "502", name: "Blue Green", color: "Green"),
        DMCThread(number: "503", name: "Blue Green - Medium", color: "Green"),
        DMCThread(number: "504", name: "Blue Green - Light", color: "Green"),
        DMCThread(number: "505", name: "Jade Green", color: "Green"),
        DMCThread(number: "517", name: "Wedgewood - Dark", color: "Blue"),
        DMCThread(number: "518", name: "Wedgewood - Light", color: "Blue"),
        DMCThread(number: "519", name: "Sky Blue", color: "Blue"),
        DMCThread(number: "520", name: "Fern Green - Dark", color: "Green"),
        DMCThread(number: "522", name: "Fern Green", color: "Green"),
        DMCThread(number: "523", name: "Fern Green - Light", color: "Green"),
        DMCThread(number: "524", name: "Fern Green - Very Light", color: "Green"),
        DMCThread(number: "535", name: "Ash Gray - Very Light", color: "Gray"),
        DMCThread(number: "543", name: "Beige Brown - Ultra Very Light", color: "Brown"),
        DMCThread(number: "550", name: "Violet - Very Dark", color: "Purple"),
        DMCThread(number: "552", name: "Violet - Medium", color: "Purple"),
        DMCThread(number: "553", name: "Violet", color: "Purple"),
        DMCThread(number: "554", name: "Violet - Light", color: "Purple"),
        DMCThread(number: "561", name: "Celadon Green - Very Dark", color: "Green"),
        DMCThread(number: "562", name: "Jade - Medium", color: "Green"),
        DMCThread(number: "563", name: "Jade - Light", color: "Green"),
        DMCThread(number: "564", name: "Jade - Very Light", color: "Green"),
        DMCThread(number: "580", name: "Moss Green - Dark", color: "Green"),
        DMCThread(number: "581", name: "Moss Green", color: "Green"),
        DMCThread(number: "597", name: "Turquoise", color: "Blue"),
        DMCThread(number: "598", name: "Turquoise - Light", color: "Blue"),
        DMCThread(number: "600", name: "Cranberry - Very Dark", color: "Red"),
        DMCThread(number: "601", name: "Cranberry - Dark", color: "Red"),
        DMCThread(number: "602", name: "Cranberry - Medium", color: "Red"),
        DMCThread(number: "603", name: "Cranberry", color: "Red"),
        DMCThread(number: "604", name: "Cranberry - Light", color: "Red"),
        DMCThread(number: "605", name: "Cranberry - Very Light", color: "Red"),
        DMCThread(number: "606", name: "Orange-Red - Bright", color: "Orange"),
        DMCThread(number: "608", name: "Orange-Red - Bright", color: "Orange"),
        DMCThread(number: "610", name: "Drab Brown - Very Dark", color: "Brown"),
        DMCThread(number: "611", name: "Drab Brown", color: "Brown"),
        DMCThread(number: "612", name: "Drab Brown - Light", color: "Brown"),
        DMCThread(number: "613", name: "Drab Brown - Very Light", color: "Brown"),
        DMCThread(number: "632", name: "Desert Sand - Ultra Very Dark", color: "Brown"),
        DMCThread(number: "640", name: "Beige Gray - Very Dark", color: "Gray"),
        DMCThread(number: "642", name: "Beige Gray - Dark", color: "Gray"),
        DMCThread(number: "644", name: "Beige Gray - Medium", color: "Gray"),
        DMCThread(number: "645", name: "Beige Gray - Light", color: "Gray"),
        DMCThread(number: "646", name: "Beaver Gray - Medium", color: "Gray"),
        DMCThread(number: "647", name: "Beaver Gray - Light", color: "Gray"),
        DMCThread(number: "648", name: "Beaver Gray - Very Light", color: "Gray"),
        DMCThread(number: "666", name: "Bright Red", color: "Red"),
        DMCThread(number: "676", name: "Old Gold - Light", color: "Yellow"),
        DMCThread(number: "677", name: "Old Gold - Very Light", color: "Yellow"),
        DMCThread(number: "680", name: "Old Gold - Dark", color: "Yellow"),
        DMCThread(number: "699", name: "Green", color: "Green"),
        DMCThread(number: "700", name: "Green - Bright", color: "Green"),
        DMCThread(number: "701", name: "Green - Light", color: "Green"),
        DMCThread(number: "702", name: "Kelly Green", color: "Green"),
        DMCThread(number: "703", name: "Chartreuse", color: "Green"),
        DMCThread(number: "704", name: "Chartreuse - Bright", color: "Green"),
        DMCThread(number: "712", name: "Cream", color: "White"),
        DMCThread(number: "718", name: "Plum", color: "Purple"),
        DMCThread(number: "720", name: "Orange Spice - Dark", color: "Orange"),
        DMCThread(number: "721", name: "Orange Spice - Medium", color: "Orange"),
        DMCThread(number: "722", name: "Orange Spice - Light", color: "Orange"),
        DMCThread(number: "725", name: "Topaz - Medium Light", color: "Yellow"),
        DMCThread(number: "726", name: "Topaz - Light", color: "Yellow"),
        DMCThread(number: "727", name: "Topaz - Very Light", color: "Yellow"),
        DMCThread(number: "729", name: "Old Gold - Medium", color: "Yellow"),
        DMCThread(number: "730", name: "Olive Green - Very Dark", color: "Green"),
        DMCThread(number: "731", name: "Olive Green - Dark", color: "Green"),
        DMCThread(number: "732", name: "Olive Green", color: "Green"),
        DMCThread(number: "733", name: "Olive Green - Medium", color: "Green"),
        DMCThread(number: "734", name: "Olive Green - Light", color: "Green"),
        DMCThread(number: "738", name: "Tan - Very Light", color: "Brown"),
        DMCThread(number: "739", name: "Tan - Ultra Very Light", color: "Brown"),
        DMCThread(number: "740", name: "Tangerine", color: "Orange"),
        DMCThread(number: "741", name: "Tangerine - Medium", color: "Orange"),
        DMCThread(number: "742", name: "Tangerine - Light", color: "Orange"),
        DMCThread(number: "743", name: "Yellow - Medium", color: "Yellow"),
        DMCThread(number: "744", name: "Yellow - Pale", color: "Yellow"),
        DMCThread(number: "745", name: "Yellow - Light Pale", color: "Yellow"),
        DMCThread(number: "746", name: "Off White", color: "White"),
        DMCThread(number: "747", name: "Peacock Blue - Very Light", color: "Blue"),
        DMCThread(number: "754", name: "Peach - Light", color: "Orange"),
        DMCThread(number: "758", name: "Terra Cotta - Very Light", color: "Brown"),
        DMCThread(number: "760", name: "Salmon", color: "Red"),
        DMCThread(number: "761", name: "Salmon - Light", color: "Red"),
        DMCThread(number: "762", name: "Pearl Gray - Very Light", color: "Gray"),
        DMCThread(number: "772", name: "Yellow Green - Very Light", color: "Green"),
        DMCThread(number: "775", name: "Baby Blue - Very Light", color: "Blue"),
        DMCThread(number: "776", name: "Pink - Medium", color: "Pink"),
        DMCThread(number: "777", name: "Raspberry - Very Dark", color: "Red"),
        DMCThread(number: "778", name: "Antique Mauve - Very Light", color: "Purple"),
        DMCThread(number: "779", name: "Cocoa - Dark", color: "Brown"),
        DMCThread(number: "780", name: "Topaz - Ultra Very Dark", color: "Yellow"),
        DMCThread(number: "781", name: "Topaz - Very Dark", color: "Yellow"),
        DMCThread(number: "782", name: "Topaz - Dark", color: "Yellow"),
        DMCThread(number: "783", name: "Topaz - Medium", color: "Yellow"),
        DMCThread(number: "791", name: "Cornflower Blue - Very Dark", color: "Blue"),
        DMCThread(number: "792", name: "Cornflower Blue - Dark", color: "Blue"),
        DMCThread(number: "793", name: "Cornflower Blue - Medium", color: "Blue"),
        DMCThread(number: "794", name: "Cornflower Blue - Light", color: "Blue"),
        DMCThread(number: "796", name: "Royal Blue - Dark", color: "Blue"),
        DMCThread(number: "797", name: "Royal Blue", color: "Blue"),
        DMCThread(number: "798", name: "Delft Blue - Dark", color: "Blue"),
        DMCThread(number: "799", name: "Delft Blue - Medium", color: "Blue"),
        DMCThread(number: "800", name: "Delft Blue - Pale", color: "Blue"),
        DMCThread(number: "801", name: "Coffee Brown - Dark", color: "Brown"),
        DMCThread(number: "803", name: "Baby Blue - Ultra Very Dark", color: "Blue"),
        DMCThread(number: "806", name: "Peacock Blue - Dark", color: "Blue"),
        DMCThread(number: "807", name: "Peacock Blue", color: "Blue"),
        DMCThread(number: "809", name: "Delft Blue", color: "Blue"),
        DMCThread(number: "813", name: "Blue - Light", color: "Blue"),
        DMCThread(number: "814", name: "Garnet - Dark", color: "Red"),
        DMCThread(number: "815", name: "Garnet - Medium", color: "Red"),
        DMCThread(number: "816", name: "Garnet", color: "Red"),
        DMCThread(number: "817", name: "Coral Red - Very Dark", color: "Red"),
        DMCThread(number: "818", name: "Baby Pink", color: "Pink"),
        DMCThread(number: "819", name: "Baby Pink - Light", color: "Pink"),
        DMCThread(number: "820", name: "Royal Blue - Very Dark", color: "Blue"),
        DMCThread(number: "822", name: "Beige Gray - Light", color: "Gray"),
        DMCThread(number: "823", name: "Navy Blue - Dark", color: "Blue"),
        DMCThread(number: "824", name: "Blue - Very Dark", color: "Blue"),
        DMCThread(number: "825", name: "Blue - Dark", color: "Blue"),
        DMCThread(number: "826", name: "Blue - Medium", color: "Blue"),
        DMCThread(number: "827", name: "Blue - Very Light", color: "Blue"),
        DMCThread(number: "828", name: "Blue - Ultra Very Light", color: "Blue"),
        DMCThread(number: "829", name: "Golden Olive - Very Dark", color: "Green"),
        DMCThread(number: "830", name: "Golden Olive - Dark", color: "Green"),
        DMCThread(number: "831", name: "Golden Olive - Medium", color: "Green"),
        DMCThread(number: "832", name: "Golden Olive", color: "Green"),
        DMCThread(number: "833", name: "Golden Olive - Light", color: "Green"),
        DMCThread(number: "834", name: "Golden Olive - Very Light", color: "Green"),
        DMCThread(number: "838", name: "Beige Brown - Very Dark", color: "Brown"),
        DMCThread(number: "839", name: "Beige Brown - Dark", color: "Brown"),
        DMCThread(number: "840", name: "Beige Brown - Medium", color: "Brown"),
        DMCThread(number: "841", name: "Beige Brown - Light", color: "Brown"),
        DMCThread(number: "842", name: "Beige Brown - Very Light", color: "Brown"),
        DMCThread(number: "844", name: "Beaver Gray - Ultra Dark", color: "Gray"),
        DMCThread(number: "869", name: "Hazel Nut Brown - Very Dark", color: "Brown"),
        DMCThread(number: "890", name: "Pistachio Green - Ultra Very Dark", color: "Green"),
        DMCThread(number: "891", name: "Carnation - Dark", color: "Red"),
        DMCThread(number: "892", name: "Carnation - Medium", color: "Red"),
        DMCThread(number: "893", name: "Carnation - Light", color: "Red"),
        DMCThread(number: "894", name: "Carnation - Very Light", color: "Red"),
        DMCThread(number: "895", name: "Hunter Green - Very Dark", color: "Green"),
        DMCThread(number: "898", name: "Coffee Brown - Very Dark", color: "Brown"),
        DMCThread(number: "899", name: "Rose - Medium", color: "Red"),
        DMCThread(number: "900", name: "Burnt Orange - Dark", color: "Orange"),
        DMCThread(number: "902", name: "Garnet - Very Dark", color: "Red"),
        DMCThread(number: "904", name: "Parrot Green - Very Dark", color: "Green"),
        DMCThread(number: "905", name: "Parrot Green - Dark", color: "Green"),
        DMCThread(number: "906", name: "Parrot Green - Medium", color: "Green"),
        DMCThread(number: "907", name: "Parrot Green - Light", color: "Green"),
        DMCThread(number: "909", name: "Emerald Green - Very Dark", color: "Green"),
        DMCThread(number: "910", name: "Emerald Green - Dark", color: "Green"),
        DMCThread(number: "911", name: "Emerald Green - Medium", color: "Green"),
        DMCThread(number: "912", name: "Emerald Green - Light", color: "Green"),
        DMCThread(number: "913", name: "Nile Green - Medium", color: "Green"),
        DMCThread(number: "915", name: "Plum - Dark", color: "Purple"),
        DMCThread(number: "917", name: "Plum - Medium", color: "Purple"),
        DMCThread(number: "918", name: "Red Copper - Dark", color: "Brown"),
        DMCThread(number: "919", name: "Red Copper", color: "Brown"),
        DMCThread(number: "920", name: "Copper - Medium", color: "Brown"),
        DMCThread(number: "921", name: "Copper", color: "Brown"),
        DMCThread(number: "922", name: "Copper - Light", color: "Brown"),
        DMCThread(number: "924", name: "Gray Green - Very Dark", color: "Green"),
        DMCThread(number: "926", name: "Gray Green - Medium", color: "Green"),
        DMCThread(number: "927", name: "Gray Green - Light", color: "Green"),
        DMCThread(number: "928", name: "Gray Green - Very Light", color: "Green"),
        DMCThread(number: "930", name: "Antique Blue - Dark", color: "Blue"),
        DMCThread(number: "931", name: "Antique Blue - Medium", color: "Blue"),
        DMCThread(number: "932", name: "Antique Blue - Light", color: "Blue"),
        DMCThread(number: "934", name: "Avocado Green - Black", color: "Green"),
        DMCThread(number: "935", name: "Avocado Green - Dark", color: "Green"),
        DMCThread(number: "936", name: "Avocado Green - Very Dark", color: "Green"),
        DMCThread(number: "937", name: "Avocado Green - Medium", color: "Green"),
        DMCThread(number: "938", name: "Coffee Brown - Ultra Dark", color: "Brown"),
        DMCThread(number: "939", name: "Navy Blue - Very Dark", color: "Blue"),
        DMCThread(number: "943", name: "Green Bright - Medium", color: "Green"),
        DMCThread(number: "945", name: "Tawny", color: "Brown"),
        DMCThread(number: "946", name: "Burnt Orange - Medium", color: "Orange"),
        DMCThread(number: "947", name: "Burnt Orange", color: "Orange"),
        DMCThread(number: "948", name: "Peach - Very Light", color: "Orange"),
        DMCThread(number: "950", name: "Desert Sand - Light", color: "Brown"),
        DMCThread(number: "951", name: "Tawny - Light", color: "Brown"),
        DMCThread(number: "954", name: "Nile Green", color: "Green"),
        DMCThread(number: "955", name: "Nile Green - Light", color: "Green"),
        DMCThread(number: "956", name: "Geranium", color: "Red"),
        DMCThread(number: "957", name: "Geranium - Pale", color: "Red"),
        DMCThread(number: "958", name: "Sea Green - Dark", color: "Green"),
        DMCThread(number: "959", name: "Sea Green - Medium", color: "Green"),
        DMCThread(number: "961", name: "Dusty Rose - Dark", color: "Red"),
        DMCThread(number: "962", name: "Dusty Rose - Medium", color: "Red"),
        DMCThread(number: "963", name: "Dusty Rose - Ultra Very Light", color: "Red"),
        DMCThread(number: "964", name: "Sea Green - Light", color: "Green"),
        DMCThread(number: "966", name: "Jade - Ultra Very Light", color: "Green"),
        DMCThread(number: "970", name: "Pumpkin - Light", color: "Orange"),
        DMCThread(number: "971", name: "Pumpkin", color: "Orange"),
        DMCThread(number: "972", name: "Canary - Deep", color: "Yellow"),
        DMCThread(number: "973", name: "Canary - Bright", color: "Yellow"),
        DMCThread(number: "975", name: "Golden Brown - Dark", color: "Brown"),
        DMCThread(number: "976", name: "Golden Brown - Medium", color: "Brown"),
        DMCThread(number: "977", name: "Golden Brown - Light", color: "Brown"),
        DMCThread(number: "986", name: "Forest Green - Very Dark", color: "Green"),
        DMCThread(number: "987", name: "Forest Green - Dark", color: "Green"),
        DMCThread(number: "988", name: "Forest Green - Medium", color: "Green"),
        DMCThread(number: "989", name: "Forest Green", color: "Green"),
        DMCThread(number: "991", name: "Aquamarine - Dark", color: "Blue"),
        DMCThread(number: "992", name: "Aquamarine - Light", color: "Blue"),
        DMCThread(number: "993", name: "Aquamarine - Very Light", color: "Blue"),
        DMCThread(number: "995", name: "Electric Blue - Dark", color: "Blue"),
        DMCThread(number: "996", name: "Electric Blue - Medium", color: "Blue"),
        DMCThread(number: "3011", name: "Khaki Green - Dark", color: "Green"),
        DMCThread(number: "3012", name: "Khaki Green - Medium", color: "Green"),
        DMCThread(number: "3013", name: "Khaki Green - Light", color: "Green"),
        DMCThread(number: "3021", name: "Brown Gray - Very Dark", color: "Gray"),
        DMCThread(number: "3022", name: "Brown Gray - Medium", color: "Gray"),
        DMCThread(number: "3023", name: "Brown Gray - Light", color: "Gray"),
        DMCThread(number: "3024", name: "Brown Gray - Very Light", color: "Gray"),
        DMCThread(number: "3031", name: "Mocha Brown - Very Dark", color: "Brown"),
        DMCThread(number: "3032", name: "Mocha Brown - Medium", color: "Brown"),
        DMCThread(number: "3033", name: "Mocha Brown - Very Light", color: "Brown"),
        DMCThread(number: "3041", name: "Antique Violet - Very Dark", color: "Purple"),
        DMCThread(number: "3042", name: "Antique Violet - Medium", color: "Purple"),
        DMCThread(number: "3045", name: "Yellow Beige - Dark", color: "Brown"),
        DMCThread(number: "3046", name: "Yellow Beige - Medium", color: "Brown"),
        DMCThread(number: "3047", name: "Yellow Beige - Light", color: "Brown"),
        DMCThread(number: "3051", name: "Green Gray - Dark", color: "Green"),
        DMCThread(number: "3052", name: "Green Gray - Medium", color: "Green"),
        DMCThread(number: "3053", name: "Green Gray - Light", color: "Green"),
        DMCThread(number: "3064", name: "Desert Sand", color: "Brown"),
        DMCThread(number: "3072", name: "Beaver Gray - Very Light", color: "Gray"),
        DMCThread(number: "3078", name: "Golden Yellow - Very Light", color: "Yellow"),
        DMCThread(number: "3325", name: "Baby Blue - Light", color: "Blue"),
        DMCThread(number: "3326", name: "Rose - Light", color: "Red"),
        DMCThread(number: "3328", name: "Salmon - Dark", color: "Red"),
        DMCThread(number: "3340", name: "Apricot - Medium", color: "Orange"),
        DMCThread(number: "3341", name: "Apricot", color: "Orange"),
        DMCThread(number: "3345", name: "Hunter Green - Dark", color: "Green"),
        DMCThread(number: "3346", name: "Hunter Green", color: "Green"),
        DMCThread(number: "3347", name: "Yellow Green - Medium", color: "Green"),
        DMCThread(number: "3348", name: "Yellow Green - Light", color: "Green"),
        DMCThread(number: "3350", name: "Dusty Rose - Ultra Dark", color: "Red"),
        DMCThread(number: "3354", name: "Dusty Rose - Light", color: "Red"),
        DMCThread(number: "3362", name: "Pine Green - Dark", color: "Green"),
        DMCThread(number: "3363", name: "Pine Green - Medium", color: "Green"),
        DMCThread(number: "3364", name: "Pine Green", color: "Green"),
        DMCThread(number: "3371", name: "Black Brown", color: "Brown"),
        DMCThread(number: "3607", name: "Plum - Light", color: "Purple"),
        DMCThread(number: "3608", name: "Plum - Very Light", color: "Purple"),
        DMCThread(number: "3609", name: "Plum - Ultra Very Light", color: "Purple"),
        DMCThread(number: "3685", name: "Mauve - Very Dark", color: "Purple"),
        DMCThread(number: "3687", name: "Mauve", color: "Purple"),
        DMCThread(number: "3688", name: "Mauve - Medium", color: "Purple"),
        DMCThread(number: "3689", name: "Mauve - Light", color: "Purple"),
        DMCThread(number: "1", name: "White Tin", color: "White Tin"),
        DMCThread(number: "2", name: "Tin", color: "Tin"),
        DMCThread(number: "3", name: "Pink Tin", color: "Pink"),
        DMCThread(number: "4", name: "Coral Tin", color: "Coral"),
        DMCThread(number: "5", name: "Rose Tin", color: "Rose"),
        DMCThread(number: "6", name: "Red Tin", color: "Red"),
        DMCThread(number: "7", name: "Burgundy Tin", color: "Burgundy"),
        DMCThread(number: "8", name: "Orange Tin", color: "Orange"),
        DMCThread(number: "9", name: "Yellow Tin", color: "Yellow"),
        DMCThread(number: "10", name: "Green Tin", color: "Green"),
        DMCThread(number: "11", name: "Blue Tin", color: "Blue"),
        DMCThread(number: "12", name: "Purple Tin", color: "Purple"),
        DMCThread(number: "13", name: "Brown Tin", color: "Brown"),
        DMCThread(number: "14", name: "Black Tin", color: "Black"),
        DMCThread(number: "16", name: "Tin", color: "Tin"),
        DMCThread(number: "17", name: "Pink", color: "Pink"),
        DMCThread(number: "18", name: "Coral", color: "Coral"),
        DMCThread(number: "19", name: "Rose", color: "Rose"),
        DMCThread(number: "20", name: "Red", color: "Red"),
        DMCThread(number: "21", name: "Burgundy", color: "Burgundy"),
        DMCThread(number: "22", name: "Orange", color: "Orange"),
        DMCThread(number: "23", name: "Yellow", color: "Yellow"),
        DMCThread(number: "24", name: "Green", color: "Green"),
        DMCThread(number: "25", name: "Blue", color: "Blue"),
        DMCThread(number: "26", name: "Purple", color: "Purple"),
        DMCThread(number: "27", name: "Brown", color: "Brown"),
        DMCThread(number: "28", name: "Black", color: "Black"),
        DMCThread(number: "29", name: "White", color: "White"),
        DMCThread(number: "30", name: "Tin", color: "Tin"),
        DMCThread(number: "31", name: "Pink", color: "Pink"),
        DMCThread(number: "32", name: "Coral", color: "Coral"),
        DMCThread(number: "33", name: "Rose", color: "Rose"),
        DMCThread(number: "34", name: "Red", color: "Red"),
        DMCThread(number: "35", name: "Burgundy", color: "Burgundy"),
        DMCThread(number: "36", name: "Orange", color: "Orange"),
        DMCThread(number: "37", name: "Yellow", color: "Yellow"),
        DMCThread(number: "38", name: "Green", color: "Green"),
        DMCThread(number: "39", name: "Blue", color: "Blue"),
        DMCThread(number: "40", name: "Purple", color: "Purple"),
        DMCThread(number: "41", name: "Brown", color: "Brown"),
        DMCThread(number: "42", name: "Black", color: "Black"),
        DMCThread(number: "43", name: "White", color: "White"),
        DMCThread(number: "44", name: "Tin", color: "Tin"),
        DMCThread(number: "45", name: "Pink", color: "Pink"),
        DMCThread(number: "46", name: "Coral", color: "Coral"),
        DMCThread(number: "47", name: "Rose", color: "Rose"),
        DMCThread(number: "48", name: "Red", color: "Red"),
        DMCThread(number: "49", name: "Burgundy", color: "Burgundy"),
        DMCThread(number: "50", name: "Orange", color: "Orange"),
        DMCThread(number: "51", name: "Yellow", color: "Yellow"),
        DMCThread(number: "52", name: "Green", color: "Green"),
        DMCThread(number: "53", name: "Blue", color: "Blue"),
        DMCThread(number: "54", name: "Purple", color: "Purple"),
        DMCThread(number: "55", name: "Brown", color: "Brown"),
        DMCThread(number: "56", name: "Black", color: "Black"),
        DMCThread(number: "57", name: "White", color: "White"),
        DMCThread(number: "58", name: "Tin", color: "Tin"),
        DMCThread(number: "59", name: "Pink", color: "Pink"),
        DMCThread(number: "60", name: "Coral", color: "Coral"),
        DMCThread(number: "61", name: "Rose", color: "Rose"),
        DMCThread(number: "62", name: "Red", color: "Red"),
        DMCThread(number: "63", name: "Burgundy", color: "Burgundy"),
        DMCThread(number: "64", name: "Orange", color: "Orange"),
        DMCThread(number: "65", name: "Yellow", color: "Yellow"),
        DMCThread(number: "66", name: "Green", color: "Green"),
        DMCThread(number: "67", name: "Blue", color: "Blue"),
        DMCThread(number: "68", name: "Purple", color: "Purple"),
        DMCThread(number: "69", name: "Brown", color: "Brown"),
        DMCThread(number: "70", name: "Black", color: "Black"),
        DMCThread(number: "71", name: "White", color: "White"),
        DMCThread(number: "72", name: "Tin", color: "Tin"),
        DMCThread(number: "73", name: "Pink", color: "Pink"),
        DMCThread(number: "74", name: "Coral", color: "Coral"),
        DMCThread(number: "75", name: "Rose", color: "Rose"),
        DMCThread(number: "76", name: "Red", color: "Red"),
        DMCThread(number: "77", name: "Burgundy", color: "Burgundy"),
        DMCThread(number: "78", name: "Orange", color: "Orange"),
        DMCThread(number: "79", name: "Yellow", color: "Yellow"),
        DMCThread(number: "80", name: "Green", color: "Green"),
        DMCThread(number: "81", name: "Blue", color: "Blue"),
        DMCThread(number: "82", name: "Purple", color: "Purple"),
        DMCThread(number: "83", name: "Brown", color: "Brown"),
        DMCThread(number: "84", name: "Black", color: "Black"),
        DMCThread(number: "85", name: "White", color: "White"),
        DMCThread(number: "86", name: "Tin", color: "Tin"),
        DMCThread(number: "87", name: "Pink", color: "Pink"),
        DMCThread(number: "88", name: "Coral", color: "Coral"),
        DMCThread(number: "89", name: "Rose", color: "Rose"),
        DMCThread(number: "90", name: "Red", color: "Red"),
        DMCThread(number: "91", name: "Burgundy", color: "Burgundy"),
        DMCThread(number: "92", name: "Orange", color: "Orange"),
        DMCThread(number: "93", name: "Yellow", color: "Yellow"),
        DMCThread(number: "94", name: "Green", color: "Green"),
        DMCThread(number: "95", name: "Blue", color: "Blue"),
        DMCThread(number: "96", name: "Purple", color: "Purple"),
        DMCThread(number: "97", name: "Brown", color: "Brown"),
        DMCThread(number: "98", name: "Black", color: "Black"),
        DMCThread(number: "99", name: "White", color: "White"),
        DMCThread(number: "100", name: "Tin", color: "Tin"),
        DMCThread(number: "550", name: "Violet - Very Dark", color: "Purple"),
        DMCThread(number: "552", name: "Violet - Medium", color: "Purple"),
        DMCThread(number: "553", name: "Violet", color: "Purple"),
        DMCThread(number: "554", name: "Violet - Light", color: "Purple"),
        DMCThread(number: "561", name: "Celadon Green - Very Dark", color: "Green"),
        DMCThread(number: "562", name: "Jade - Medium", color: "Green"),
        DMCThread(number: "563", name: "Jade - Light", color: "Green"),
        DMCThread(number: "564", name: "Jade - Very Light", color: "Green"),
        DMCThread(number: "580", name: "Moss Green - Dark", color: "Green"),
        DMCThread(number: "581", name: "Moss Green", color: "Green"),
        DMCThread(number: "597", name: "Turquoise", color: "Blue"),
        DMCThread(number: "598", name: "Turquoise - Light", color: "Blue"),
        DMCThread(number: "600", name: "Cranberry - Very Dark", color: "Red"),
        DMCThread(number: "601", name: "Cranberry - Dark", color: "Red"),
        DMCThread(number: "602", name: "Cranberry - Medium", color: "Red"),
        DMCThread(number: "603", name: "Cranberry", color: "Red"),
        DMCThread(number: "604", name: "Cranberry - Light", color: "Red"),
        DMCThread(number: "605", name: "Cranberry - Very Light", color: "Red"),
        DMCThread(number: "606", name: "Orange-Red - Bright", color: "Orange"),
        DMCThread(number: "608", name: "Orange-Red - Bright", color: "Orange"),
        DMCThread(number: "610", name: "Drab Brown - Very Dark", color: "Brown"),
        DMCThread(number: "611", name: "Drab Brown", color: "Brown"),
        DMCThread(number: "612", name: "Drab Brown - Light", color: "Brown"),
        DMCThread(number: "613", name: "Drab Brown - Very Light", color: "Brown")
    ]
} 